name: fetch

on:
  schedule:
    - cron: '0 * * * *'  
  workflow_dispatch:  

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl https://your-deployment-url.com/api/cron